[[manager.prepend_keymap]]
on  = "M"
run = "plugin mount"
[[manager.prepend_keymap]]
on  = ["f","f"] 
run = "plugin fzf"
[[manager.prepend_keymap]]
on = ["f", "r"]
run = "plugin fr rg"
desc = "Search file by content (rg)"

[[manager.prepend_keymap]]
on = ["f", "a"]
run = "plugin fr rga"
desc = "Search file by content (rga)"
